### ISSUE TITLE
problem for the paper Regime Inference for Sound Floating-Point Optimizations

### ISSUE THREAD

**Issue by zuoyanzhang** [malyzajko/daisy#10]
In this paper,using Daisy mixed-tuning to test half-double,example: daisy/testcases/regime-inference/half_error/azimuth_64.scala,what instructions do I need to enter for bottom+genetic or bottom+top?.Thank you very much!

**Comment by malyzajko** [comment]
Hi,

you should first compile Daisy and generate a "daisy" script (run the following from the top directory):
`./scripts/regime-inference/compile_daisy.sh`

To then run Daisy with bottom+genetic:
`./daisy --mixed-tuning --subdiv --regime-inf --errorMethod=affineMPFR --mixed-cost-function=simple --regime-strategy=bottomGenetic --codegen --lang=C --benchmarking --bound=1000000 --silent PATH_TO_INPUT_FILE`

Replace 'bottomGenetic' for 'bottomTop' to run bottom+top. If you remove the '--silent' option, Daisy will also print some intermediate information. 

There are also scripts for running Daisy on several benchmarks (in one directory) at once in scripts/regime-inference/, see the README file (scripts/regime-inference/README.md) for more instructions.
