### ISSUE TITLE
Hello，Can I specify precision (like only use double and quad) when I use mixed-precision  function

### ISSUE THREAD

**Issue by zhangsanLIS** [malyzajko/daisy#11]

**Comment by zhangsanLIS** [comment]
I found that when I use  flags like --mixed-tuning --lang=C --codegen , the code will appear qd_real type， but what I want is  only quad and double, what should I do to achieve my goal, thanks a lot

**Comment by malyzajko** [comment]
Master still has the older version of the code generator. You can try the 'regimes' branch, which is using quadmath.h. Only these two are currently supported. (The mixed-precision tuning algorithm is the same on both branches.)

**Comment by zhangsanLIS** [comment]
> Master still has the older version of the code generator. You can try the 'regimes' branch, which is using quadmath.h. Only these two are currently supported. (The mixed-precision tuning algorithm is the same on both branches.)

sorry the question has been solved
