### ISSUE TITLE
Looking forward to your answer

### ISSUE THREAD

**Issue by zuoyanzhang** [malyzajko/daisy#15]
Hello professor, can the daisy tool measure the maximum ulp error of an expression? What I know so far is that the daisy tool can get the absolute error of the expression, or do you know of any error detection tools that can get the ulp error of the expression. Thank you very much if you can answer some of my questions

**Comment by malyzajko** [comment]
Hi!
Daisy computes the worst-case absolute error of an expression. It also prints a relative error (when the output range does not include zero and the relative error is thus well-defined), and has a specialized analysis for relative errors (called using the --analysis=relative flag), but it does not compute ulp.
