### ISSUE TITLE
Web version not available?

### ISSUE THREAD

**Issue by touisteur** [malyzajko/daisy#9]
Hi,

I wanted to try out Daisy through the Web interface mentioned in the readme.md (link : http://daisy.mpi-sws.org/ ) and I'm getting an error, telling the site is in maintenance. Is the 'live' version abandoned?

Thanks in advance.

**Comment by malyzajko** [comment]
It's working again, there was indeed maintenance after which the Daisy app was not restarted. Thanks for letting me know!

**Comment by fvolchyok** [comment]
Hi! It seems like web version is no longer available (https://daisy.mpi-sws.org). Is it expected? Even if it's fixed - is it feasible to use it today or it may be outdated and I should use offline tools directly?

**Comment by malyzajko** [comment]
Hi, indeed, the web version is no longer available. You will need to use Daisy offline/locally - feel free to message me if you have issues with the installation.
